const CONTEXT_PREFIX_PATTERN =
  /^(User workspace path:[^\n]*|User is viewing project:[^\n]*|User is viewing:[^\n]*)/u;

function looksLikeWorkspacePathToken(token: string): boolean {
  if (!token) return false;
  return (
    token.startsWith('/') ||
    token.startsWith('~/') ||
    token.startsWith('./') ||
    token.startsWith('../') ||
    /^[A-Za-z]:\\/.test(token)
  );
}

export function normalizeChatContentForMatch(content: string): string {
  return content.replace(/\s+/g, ' ').trim();
}

export function unwrapGatewayContextWrappedUserContent(content: string): string | null {
  const normalized = content.replace(/\r\n/g, '\n').trim();
  if (!normalized) return null;

  // Canonical wrapper format generated by sendMessageWithContext.
  const canonicalMatch = normalized.match(
    /^(User workspace path:[^\n]*|User is viewing project:[^\n]*|User is viewing:[^\n]*)\n\n([\s\S]+)$/u,
  );
  if (canonicalMatch) {
    const unwrapped = canonicalMatch[2]?.trim();
    return unwrapped && unwrapped.length > 0 ? unwrapped : null;
  }

  // Some transports flatten double-newline wrappers to a single newline.
  const singleNewlineMatch = normalized.match(
    /^(User workspace path:[^\n]*|User is viewing project:[^\n]*|User is viewing:[^\n]*)\n+([\s\S]+)$/u,
  );
  if (singleNewlineMatch) {
    const unwrapped = singleNewlineMatch[2]?.trim();
    return unwrapped && unwrapped.length > 0 ? unwrapped : null;
  }

  // Some history payloads flatten newlines into spaces. Handle workspace-path
  // context specifically because the path token is parseable.
  if (normalized.startsWith('User workspace path:')) {
    const remainder = normalized.slice('User workspace path:'.length).trimStart();
    const collapsedMatch = remainder.match(/^([^\s]+)\s+([\s\S]+)$/u);
    if (collapsedMatch && looksLikeWorkspacePathToken(collapsedMatch[1])) {
      const unwrapped = collapsedMatch[2]?.trim();
      return unwrapped && unwrapped.length > 0 ? unwrapped : null;
    }
  }

  // Generic fallback: if a known prefix exists and there is a visible block
  // separator, trust the latter half as user content.
  const prefix = normalized.match(CONTEXT_PREFIX_PATTERN)?.[0];
  if (prefix) {
    const remainder = normalized.slice(prefix.length).trimStart();
    const splitIndex = remainder.search(/\n{2,}|\s{2,}/u);
    if (splitIndex >= 0) {
      const maybeUserText = remainder.slice(splitIndex).trim();
      if (maybeUserText.length > 0) return maybeUserText;
    }
  }

  return null;
}

export function normalizeChatContentWithContextUnwrap(content: string): string {
  const unwrapped = unwrapGatewayContextWrappedUserContent(content);
  return normalizeChatContentForMatch(unwrapped ?? content);
}
