const CONTEXT_PREFIX_PATTERN =
  /^(User workspace path:[^\n]*|User is viewing project:[^\n]*|User is viewing:[^\n]*)/u;
const USER_REQUEST_MARKER = 'User request:';

/**
 * Strip OpenClaw envelope metadata from user message content for display.
 *
 * OpenClaw wraps user messages with context blocks:
 * - `Conversation info (untrusted metadata):` + JSON code block
 * - `[Thu 2026-02-19 05:15 GMT]` timestamp prefix
 * - `User workspace path:` / `User request:` wrappers
 * - `[message_id: ...]` tags
 *
 * This function strips all of these, returning only the user's actual message.
 */
export function stripOpenClawEnvelope(content: string): string {
  let text = content.replace(/\r\n/g, '\n').trim();
  if (!text) return text;

  // Strip leading "Conversation info (untrusted metadata):" block with JSON code fence
  text = text.replace(
    /^Conversation info \(untrusted metadata\):\s*```json?\s*\n[\s\S]*?\n```\s*/u,
    '',
  ).trim();

  // Strip leading timestamp envelope: [Thu 2026-02-19 05:15 GMT]
  text = text.replace(
    /^\[(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s+\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}(?:\s+[A-Z]{2,5})?\]\s*/u,
    '',
  ).trim();

  // Strip "User workspace path: /path User request: " wrapper
  const requestMatch = text.match(
    /^User workspace path:\s*\S+\s+User request:\s*([\s\S]+)$/u,
  );
  if (requestMatch) {
    text = requestMatch[1].trim();
  }

  // Strip trailing [message_id: ...] tags
  text = text.replace(/\s*\[message_id:\s*[^\]]+\]\s*$/u, '').trim();

  // Reformat [Attached images: ...] as a readable line instead of stripping
  text = text.replace(
    /\s*\[Attached images?:\s*([^\]]+)\]\s*$/u,
    (_match, files: string) => `\n\n📎 ${files}`,
  ).trim();

  return text;
}

function looksLikeWorkspacePathToken(token: string): boolean {
  if (!token) return false;
  return (
    token.startsWith('/') ||
    token.startsWith('~/') ||
    token.startsWith('./') ||
    token.startsWith('../') ||
    /^[A-Za-z]:\\/.test(token)
  );
}

export function normalizeChatContentForMatch(content: string): string {
  return content.replace(/\s+/g, ' ').trim();
}

export function unwrapGatewayContextWrappedUserContent(content: string): string | null {
  let normalized = content.replace(/\r\n/g, '\n').trim();
  if (!normalized) return null;

  // Strip OpenClaw 2026.2.17+ envelope metadata that wraps the context wrapper:
  // - "Conversation info (untrusted metadata):" JSON code block
  // - [timestamp] prefix
  // - Trailing [message_id: ...] / [Attached images: ...] tags
  normalized = normalized
    .replace(
      /^Conversation info \(untrusted metadata\):\s*```json?\s*\n[\s\S]*?\n```\s*/u,
      '',
    )
    .replace(
      /^\[(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s+\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}(?:\s+[A-Z]{2,5})?\]\s*/u,
      '',
    )
    .replace(/\s*\[message_id:\s*[^\]]+\]\s*$/u, '')
    .replace(/\s*\[Attached images?:\s*[^\]]+\]\s*$/u, '')
    .trim();

  if (!normalized) return null;
  const hasKnownContextPrefix = CONTEXT_PREFIX_PATTERN.test(normalized);

  // Preferred wrapper format generated by sendMessageWithContext.
  const markedCanonicalMatch = normalized.match(
    /^(User workspace path:[^\n]*|User is viewing project:[^\n]*|User is viewing:[^\n]*)\n\nUser request:\n([\s\S]+)$/u,
  );
  if (markedCanonicalMatch) {
    const unwrapped = markedCanonicalMatch[2]?.trim();
    return unwrapped && unwrapped.length > 0 ? unwrapped : null;
  }

  const markedSingleNewlineMatch = normalized.match(
    /^(User workspace path:[^\n]*|User is viewing project:[^\n]*|User is viewing:[^\n]*)\n+User request:\n?([\s\S]+)$/u,
  );
  if (markedSingleNewlineMatch) {
    const unwrapped = markedSingleNewlineMatch[2]?.trim();
    return unwrapped && unwrapped.length > 0 ? unwrapped : null;
  }

  // Some transports flatten all newlines to spaces.
  const markerIndex = hasKnownContextPrefix ? normalized.indexOf(USER_REQUEST_MARKER) : -1;
  if (markerIndex >= 0) {
    const markerRemainder = normalized
      .slice(markerIndex + USER_REQUEST_MARKER.length)
      .trim();
    if (markerRemainder.length > 0) {
      return markerRemainder;
    }
  }

  // Canonical wrapper format generated by sendMessageWithContext.
  const canonicalMatch = normalized.match(
    /^(User workspace path:[^\n]*|User is viewing project:[^\n]*|User is viewing:[^\n]*)\n\n([\s\S]+)$/u,
  );
  if (canonicalMatch) {
    const unwrapped = canonicalMatch[2]?.trim();
    return unwrapped && unwrapped.length > 0 ? unwrapped : null;
  }

  // Some transports flatten double-newline wrappers to a single newline.
  const singleNewlineMatch = normalized.match(
    /^(User workspace path:[^\n]*|User is viewing project:[^\n]*|User is viewing:[^\n]*)\n+([\s\S]+)$/u,
  );
  if (singleNewlineMatch) {
    const unwrapped = singleNewlineMatch[2]?.trim();
    return unwrapped && unwrapped.length > 0 ? unwrapped : null;
  }

  // Some history payloads flatten newlines into spaces. Handle workspace-path
  // context specifically because the path token is parseable.
  if (normalized.startsWith('User workspace path:')) {
    const remainder = normalized.slice('User workspace path:'.length).trimStart();
    const collapsedMatch = remainder.match(/^([^\s]+)\s+([\s\S]+)$/u);
    if (collapsedMatch && looksLikeWorkspacePathToken(collapsedMatch[1])) {
      const unwrapped = collapsedMatch[2]?.trim();
      return unwrapped && unwrapped.length > 0 ? unwrapped : null;
    }
  }

  // Generic fallback: if a known prefix exists and there is a visible block
  // separator, trust the latter half as user content.
  const prefix = normalized.match(CONTEXT_PREFIX_PATTERN)?.[0];
  if (prefix) {
    const remainder = normalized.slice(prefix.length).trimStart();
    const splitIndex = remainder.search(/\n{2,}|\s{2,}/u);
    if (splitIndex >= 0) {
      const maybeUserText = remainder.slice(splitIndex).trim();
      if (maybeUserText.length > 0) return maybeUserText;
    }
  }

  return null;
}

export function normalizeChatContentWithContextUnwrap(content: string): string {
  const unwrapped = unwrapGatewayContextWrappedUserContent(content);
  return normalizeChatContentForMatch(unwrapped ?? content);
}
