#!/usr/bin/env bash
# sync-agent-compliance.sh
#
# Extracts the compliance block from AGENTS.md and injects it into
# every tool-specific config file that has COMPLIANCE markers.
#
# Usage: ./scripts/sync-agent-compliance.sh
#
# To add a new tool: add its config file to TARGETS array below.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE="$REPO_ROOT/AGENTS.md"

# ── Target files to sync compliance into ─────────────────────────────────────
TARGETS=(
  "$REPO_ROOT/CLAUDE.md"
  "$REPO_ROOT/.cursorrules"
  # "$REPO_ROOT/.github/copilot-instructions.md"
)

START_PAT="<!-- COMPLIANCE:START"
END_PAT="<!-- COMPLIANCE:END -->"

# ── Extract compliance block from AGENTS.md ──────────────────────────────────

if [[ ! -f "$SOURCE" ]]; then
  echo "ERROR: $SOURCE not found" >&2
  exit 1
fi

# Extract lines between markers (inclusive)
TMPBLOCK=$(mktemp)
inside=0
while IFS= read -r line; do
  if [[ "$line" == *"$START_PAT"* ]]; then
    inside=1
  fi
  if [[ $inside -eq 1 ]]; then
    echo "$line" >> "$TMPBLOCK"
  fi
  if [[ "$line" == *"$END_PAT"* && $inside -eq 1 ]]; then
    inside=0
  fi
done < "$SOURCE"

BLOCK_LINES=$(wc -l < "$TMPBLOCK" | tr -d ' ')
if [[ "$BLOCK_LINES" -lt 2 ]]; then
  echo "ERROR: No compliance block found in $SOURCE" >&2
  rm -f "$TMPBLOCK"
  exit 1
fi

echo "✓ Extracted compliance block from AGENTS.md ($BLOCK_LINES lines)"

# ── Inject into each target ──────────────────────────────────────────────────

inject_compliance() {
  local target="$1"
  local filename
  filename=$(basename "$target")

  if [[ ! -f "$target" ]]; then
    echo "  ⚠ $filename does not exist — creating with compliance block"
    {
      echo "# $filename — Clawchestra (AUTO-SYNCED)"
      echo "#"
      echo "# Compliance block auto-generated by scripts/sync-agent-compliance.sh"
      echo "# Edit constraints in AGENTS.md, not here."
      echo ""
      cat "$TMPBLOCK"
      echo ""
      echo "# Add tool-specific rules below this line."
    } > "$target"
    echo "  ✓ Created $filename"
    return
  fi

  # Check if the file has compliance markers
  if ! grep -q "$START_PAT" "$target"; then
    echo "  ⚠ $filename has no compliance markers — skipping"
    return
  fi

  # Build new file: before-block + new block + after-block
  local tmpfile
  tmpfile=$(mktemp)
  local state="before"

  while IFS= read -r line; do
    case "$state" in
      before)
        if [[ "$line" == *"$START_PAT"* ]]; then
          cat "$TMPBLOCK" >> "$tmpfile"
          state="inside"
        else
          echo "$line" >> "$tmpfile"
        fi
        ;;
      inside)
        if [[ "$line" == *"$END_PAT"* ]]; then
          state="after"
        fi
        # Skip all lines inside old block (replaced by TMPBLOCK which includes END marker)
        ;;
      after)
        echo "$line" >> "$tmpfile"
        ;;
    esac
  done < "$target"

  mv "$tmpfile" "$target"
  echo "  ✓ Updated $filename"
}

for target in "${TARGETS[@]}"; do
  inject_compliance "$target"
done

rm -f "$TMPBLOCK"

echo ""
echo "Done. Compliance block synced to ${#TARGETS[@]} target(s)."
